### ISSUE TITLE
[Feature Request] X11Forward supports the same feature as `openssh -Y`.

### ISSUE THREAD

**Issue by lonnywong** [blacknon/go-sshlib#33]
Is [X11Forward](https://github.com/blacknon/go-sshlib/blob/bc219a9a82a255ad100419c6f4e8eaad7ffbe2cf/forward.go#L35) exactly the same as `openssh -X`?

Is it possible to add an option to support the same feature as `openssh -Y`?

**Comment by blacknon** [comment]
I think it was probably applied in Issue #30.

**Comment by lonnywong** [comment]
Thanks. In fact, I don't know how openssh implements trusted and untrusted X11 forwarding.

**Comment by blacknon** [comment]
Sorry, I guess I didn't quite understand "ssh -Y" either.
"ssh -Y" seems to be different from PR #30.

**Comment by blacknon** [comment]
Reference Note: 

Function passing `options.forward_x11_trusted` which is the difference between -Y/-X in openssh.

https://github.com/openssh/openssh-portable/blob/88351eca17dcc55189991ba60e50819b6d4193c1/clientloop.c#L290-L451

**Comment by lonnywong** [comment]
@blacknon Thanks.
