### ISSUE TITLE
Add Reverse Dynamic Forwarding

### ISSUE THREAD

**Issue by blacknon** [blacknon/go-sshlib#7]
like OpenSSH v7.6, `ssh -R 1080`.

**Comment by MidnightSeer** [comment]
I am looking into this too (more synonymous with the -D command) - trying to figure out how to do this with the Socks proxy function

**Comment by blacknon** [comment]
openssh source code

https://github.com/openssh/openssh-portable/blob/667fec5d4fe4406745750a32f69b5d2e1a75e94b/channels.c#L1592-L1648
